name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # - name: Set up SSH Key
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    #     ssh-keyscan -H ${{ secrets.DO_SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SERVER_IP }} << 'EOF'
            set -e  # Exit immediately if any command fails

            PROJECT_DIR="/root/telex-gdrive-notifier"
            REPO_URL="git@github.com:na-cho-dev/telex-gdrive-notifier.git"
            
            if [ ! -d "$PROJECT_DIR" ]; then
                echo "Project directory does not exist. Creating..."
                mkdir -p "$PROJECT_DIR"
                git clone "$REPO_URL" "$PROJECT_DIR"
            fi

            cd "$PROJECT_DIR"

            if [ -d ".git" ]; then
                echo "Repository exists. Pulling latest changes..."
                git pull origin main
            else
                echo "Cloning repository..."
                git clone "$REPO_URL" "$PROJECT_DIR"
            fi

            npm install

            echo "Restarting the project service..."
            sudo systemctl daemon-reload
            sudo systemctl restart telex-gdrive-notifier
            sudo systemctl status telex-gdrive-notifier

            echo "Restarting Nginx..."
            sudo systemctl restart nginx

            echo "Deployment SUCCESSFUL!"
        EOF

